version: "2.3"
services:
  tests:
    build: .
    environment:
      - DB_USER=magento2
      - DB_PASS=magento2
      - DB_NAME=magento2_integration_tests
      - CONTAINER_TIMEOUT=30s
    volumes:
      - type: tmpfs
        target: /tmp:rw,exec
        volume:
          nocopy: true
      - type: tmpfs
        target: /var/lib/elasticsearch
        volume:
          nocopy: true
      - type: tmpfs
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: tmpfs
        target: /var/www/html/generated
        volume:
          nocopy: true
      - type: tmpfs
        target: /var/www/html/var
        volume:
          nocopy: true
      - type: tmpfs
        target: /dev/tests/integration/tmp
        volume:
          nocopy: true
