#!/bin/bash

ENVNAME="$1"
TESTSUITE="$2"
CHANGE_UID="$3"
CHANGE_GID="$4"

echo "$@"

until /usr/bin/healthcheck ; do
    sleep 2s
    echo "Waiting for services to come up..."
done

if [[ $# -ne 2 ]] && [[ $# -ne 4 ]]; then
    echo "Usage: $0 [env] [testsuite] <uid> <gid>"
    exit 20
fi

if [[ ! -z "$CHANGE_UID" ]] && [[ ! -z "$CHANGE_GID" ]] ; then
    echo "Starting sudo subshell with UID:$CHANGE_UID GID:$CHANGE_GID..."
    sudo -E -u "$CHANGE_UID" -g "$CHANGE_GID" $0 "$ENVNAME" "$TESTSUITE"
    exit 0
fi

set -e

function prepare_mysql() {
    mysqlshow "$DB_NAME" 2>&1 > /dev/null && return 0

    mysql -uroot -h127.0.0.1 -e "CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}'"
    mysql -uroot -h127.0.0.1 -e "GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'%' WITH GRANT OPTION"
    mysql -uroot -h127.0.0.1 -e "CREATE DATABASE ${DB_NAME}"
}

function clean() {
    rm -rf \
        /var/www/html/generated/* \
        /var/www/html/var/cache/* \
        /var/www/html/dev/tests/integration/tmp/*
}

function run_unit() {
    clean
    phing tests:unit -Denvname=${ENVNAME} -Dtestsuite=${TESTSUITE}
}

function run_integration() {
    clean
    phing tests:unit -Denvname=${ENVNAME} -Dtestsuite=${TESTSUITE}
}

prepare_mysql

run_unit
run_integration
