#!/bin/bash

# Do the "standard" build first
docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .

function build_parameterized() {
    PARAMETRIZED_TAG_PREFIX="$1"; shift
    PARAMETRIZED_IMAGE_NAME="${DOCKER_REPO}:${PARAMETRIZED_TAG_PREFIX}-${DOCKER_TAG}"

    docker build -f "${DOCKERFILE_PATH}" -t "${PARAMETRIZED_IMAGE_NAME}" . $@
    docker push "${PARAMETRIZED_IMAGE_NAME}"
}

build_parametrized "php71-es5-mysql57" --build-arg PHP_VERSION="71" --build-arg ELASTICSEARCH_VERSION="5.2.2"

build_parametrized "php71-es6-mysql57" --build-arg PHP_VERSION="71" --build-arg ELASTICSEARCH_VERSION="6.8.1"
build_parametrized "php72-es6-mysql57" --build-arg PHP_VERSION="72" --build-arg ELASTICSEARCH_VERSION="6.8.1"
build_parametrized "php73-es6-mysql57" --build-arg PHP_VERSION="73" --build-arg ELASTICSEARCH_VERSION="6.8.1"

build_parametrized "php71-es7-mysql57" --build-arg PHP_VERSION="71" --build-arg ELASTICSEARCH_VERSION="7.2.0-x86_64"
build_parametrized "php72-es7-mysql57" --build-arg PHP_VERSION="72" --build-arg ELASTICSEARCH_VERSION="7.2.0-x86_64"
build_parametrized "php73-es7-mysql57" --build-arg PHP_VERSION="73" --build-arg ELASTICSEARCH_VERSION="7.2.0-x86_64"

build_parametrized "php73-es7-mysql80" --build-arg PHP_VERSION="73" --build-arg ELASTICSEARCH_VERSION="7.2.0-x86_64" --build-arg MYSQL_VERSION="80"

