name: Build docker image

on:
  push:
    branches: [ split-integration ]
  pull_request:
    branches: [ split-integration ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./hooks/build
