name: Publish docker container to docker hub

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: ./hooks/build
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/magento-run-tests:${{ steps.vars.outputs.tag }}
        DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/magento-run-tests
    - name: Publish the Docker image
      run: ./hooks/push
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/magento-run-tests:${{ steps.vars.outputs.tag }}
        DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/magento-run-tests
